-- Insert comprehensive courses data
INSERT INTO m_courses VALUES
(201, 'Intro to Python', 'Programming', 'Learn Python basics', '{"Python": 3}', 'Online', 'Beginner', '{}', 2.5),
(202, 'Advanced Java', 'Programming', 'Deep dive into Java', '{"Java": 4}', 'Online', 'Advanced', '{"Java": 3}', 4.0),
(203, 'Machine Learning A-Z', 'Data Science', 'Full ML course', '{"Machine Learning": 4, "Python": 3}', 'Online', 'Intermediate', '{"Python": 3}', 6.0),
(204, 'Data Analysis with Excel', 'Data Analysis', 'Excel for analysis', '{"Excel": 4}', 'Offline', 'Beginner', '{}', 1.5),
(205, 'SQL for Data Analysts', 'Data Analysis', 'SQL queries', '{"SQL": 4}', 'Online', 'Intermediate', '{"Excel": 3}', 2.0),
(206, 'Leadership Essentials', 'Management', 'Lead effectively', '{"Leadership": 4}', 'Workshop', 'Intermediate', '{}', 1.0),
(207, 'Agile & Scrum', 'Project Management', 'Agile methodology', '{"Agile": 4, "Scrum": 4}', 'Online', 'Beginner', '{}', 1.5),
(208, 'AWS Certified DevOps', 'Cloud', 'AWS for DevOps', '{"AWS": 4, "Docker": 3}', 'Online', 'Advanced', '{"Linux": 3}', 5.5),
(209, 'UI Design with Figma', 'Design', 'Design interfaces', '{"Figma": 4}', 'Online', 'Beginner', '{}', 2.0),
(210, 'JIRA for Project Managers', 'Project Management', 'Track projects', '{"JIRA": 4}', 'Online', 'Beginner', '{}', 0.5),
(211, 'Microservices Architecture', 'Software Architecture', 'Service-oriented systems', '{"Microservices": 4}', 'Online', 'Advanced', '{"Java": 3}', 4.5),
(212, 'Financial Modeling', 'Finance', 'Excel for finance', '{"Excel": 4, "Finance": 4}', 'Online', 'Advanced', '{}', 3.0),
(213, 'Conflict Resolution', 'HR', 'Managing workplace conflict', '{"Conflict Resolution": 4}', 'Workshop', 'Intermediate', '{}', 1.0),
(214, 'SEO Masterclass', 'Marketing', 'SEO techniques', '{"SEO": 4}', 'Online', 'Beginner', '{}', 2.5),
(215, 'Power BI Essentials', 'Data Analysis', 'Visualize data', '{"Power BI": 3}', 'Online', 'Intermediate', '{"Excel": 3}', 2.5),
(216, 'AI Ethics', 'AI', 'Ethical considerations in AI', '{"Ethics": 4}', 'Online', 'Intermediate', '{"Machine Learning": 3}', 1.5),
(217, 'Growth Hacking Tactics', 'Marketing', 'Growth strategies', '{"Analytics": 3}', 'Online', 'Intermediate', '{}', 2.0),
(218, 'Cloud Security Basics', 'Cloud', 'Security in cloud systems', '{"Security": 3}', 'Online', 'Beginner', '{}', 1.5),
(219, 'Business Process Management', 'Business', 'Optimizing processes', '{"Analysis": 4}', 'Offline', 'Intermediate', '{}', 3.5),
(220, 'Design Systems Bootcamp', 'Design', 'Advanced design concepts', '{"Design Systems": 4}', 'Bootcamp', 'Advanced', '{"Figma": 3}', 3.5),
(221, 'React Advanced Patterns', 'Programming', 'Advanced React concepts', '{"React": 4, "JavaScript": 4}', 'Online', 'Advanced', '{"React": 3}', 3.0),
(222, 'Node.js Masterclass', 'Programming', 'Backend with Node.js', '{"Node.js": 4, "JavaScript": 4}', 'Online', 'Intermediate', '{"JavaScript": 3}', 4.0),
(223, 'Deep Learning with TensorFlow', 'Data Science', 'Neural networks', '{"Deep Learning": 4, "TensorFlow": 4}', 'Online', 'Advanced', '{"Python": 4, "ML": 3}', 5.0),
(224, 'Docker and Kubernetes', 'DevOps', 'Container orchestration', '{"Docker": 4, "Kubernetes": 4}', 'Online', 'Intermediate', '{"Linux": 3}', 3.5),
(225, 'Cybersecurity Fundamentals', 'Security', 'Security basics', '{"Cybersecurity": 4, "Network Security": 3}', 'Online', 'Beginner', '{}', 4.0),
(226, 'Product Management Strategy', 'Product', 'Product strategy', '{"Product Strategy": 4, "Analytics": 3}', 'Online', 'Intermediate', '{}', 3.0),
(227, 'Test Automation with Selenium', 'Quality', 'Automated testing', '{"Selenium": 4, "Testing": 4}', 'Online', 'Intermediate', '{"Java": 2}', 2.5),
(228, 'Digital Marketing Analytics', 'Marketing', 'Marketing metrics', '{"Analytics": 4, "SEO": 3}', 'Online', 'Intermediate', '{}', 2.0),
(229, 'Terraform Infrastructure', 'DevOps', 'Infrastructure as Code', '{"Terraform": 4, "AWS": 3}', 'Online', 'Advanced', '{"AWS": 3}', 3.0),
(230, 'UX Research Methods', 'Design', 'User research techniques', '{"User Research": 4, "Analytics": 3}', 'Online', 'Intermediate', '{}', 2.5),
(231, 'Spring Boot Microservices', 'Programming', 'Java microservices', '{"Spring Boot": 4, "Microservices": 4}', 'Online', 'Advanced', '{"Java": 4}', 4.5),
(232, 'Tableau Advanced', 'Data Analysis', 'Advanced data visualization', '{"Tableau": 4, "SQL": 3}', 'Online', 'Advanced', '{"Tableau": 2}', 3.5),
(233, 'Mobile App Testing', 'Quality', 'Testing mobile applications', '{"Mobile Testing": 4, "Automation": 3}', 'Online', 'Intermediate', '{"Testing": 3}', 2.0),
(234, 'Sales CRM Mastery', 'Sales', 'CRM best practices', '{"CRM": 4, "Sales Process": 3}', 'Online', 'Beginner', '{}', 1.5),
(235, 'Azure Cloud Fundamentals', 'Cloud', 'Microsoft Azure basics', '{"Azure": 4, "Cloud": 3}', 'Online', 'Beginner', '{}', 3.0);