-- Insert expanded roles data with 3-4 skills per role
INSERT INTO m_roles VALUES
(1, 'Software Engineer', 'Engineering', 'Junior', '{"Python": 3, "Git": 3, "SQL": 2, "Testing": 2}', 18),
(2, 'Senior Software Engineer', 'Engineering', 'Mid', '{"Java": 4, "System Design": 3, "Microservices": 3, "Leadership": 2}', 30),
(3, 'Team Lead', 'Engineering', 'Senior', '{"Leadership": 4, "Agile": 4, "Code Review": 3, "Mentoring": 3}', 42),
(4, 'Data Scientist', 'Data', 'Junior', '{"Python": 4, "Machine Learning": 3, "Statistics": 3, "SQL": 2}', 24),
(5, 'Data Analyst', 'Data', 'Junior', '{"Excel": 4, "SQL": 3, "Power BI": 3, "Statistics": 2}', 20),
(6, 'Project Manager', 'Management', 'Senior', '{"Scrum": 4, "JIRA": 4, "Stakeholder Management": 3, "Risk Management": 3}', 48),
(7, 'HR Executive', 'HR', 'Junior', '{"Communication": 4, "Recruitment": 3, "Employee Relations": 2, "Training": 2}', 22),
(8, 'HR Manager', 'HR', 'Senior', '{"Leadership": 4, "Conflict Resolution": 4, "Strategic Planning": 3, "Performance Management": 3}', 54),
(9, 'DevOps Engineer', 'Infrastructure', 'Mid', '{"AWS": 4, "Docker": 4, "Kubernetes": 3, "CI/CD": 3}', 32),
(10, 'Business Analyst', 'Business', 'Mid', '{"Analysis": 4, "Excel": 4, "Process Mapping": 3, "Requirements": 3}', 28),
(11, 'UI/UX Designer', 'Design', 'Junior', '{"Figma": 4, "User Research": 3, "Prototyping": 3, "Wireframing": 2}', 26),
(12, 'Marketing Analyst', 'Marketing', 'Junior', '{"SEO": 4, "Analytics": 3, "Social Media": 3, "Content Strategy": 2}', 24),
(13, 'Finance Analyst', 'Finance', 'Junior', '{"Excel": 4, "Finance": 4, "Financial Modeling": 3, "Risk Assessment": 2}', 30),
(14, 'Tech Lead', 'Engineering', 'Senior', '{"Microservices": 4, "Leadership": 4, "Architecture": 3, "System Design": 3}', 36),
(15, 'CTO', 'Executive', 'Executive', '{"Strategy": 4, "Technology": 4, "Leadership": 4, "Innovation": 3}', 60),
(16, 'Product Manager', 'Product', 'Mid', '{"Product Strategy": 4, "User Research": 3, "Analytics": 3, "Communication": 4}', 34),
(17, 'QA Engineer', 'Quality', 'Junior', '{"Testing": 4, "Automation": 3, "Bug Tracking": 3, "Selenium": 2}', 20),
(18, 'Senior QA Engineer', 'Quality', 'Mid', '{"Test Strategy": 4, "Automation": 4, "Leadership": 3, "CI/CD": 3}', 28),
(19, 'Security Analyst', 'Security', 'Mid', '{"Cybersecurity": 4, "Risk Assessment": 3, "Compliance": 3, "Network Security": 3}', 32),
(20, 'Content Writer', 'Marketing', 'Junior', '{"Writing": 4, "SEO": 3, "Research": 3, "Content Strategy": 2}', 18),
(21, 'Sales Executive', 'Sales', 'Junior', '{"Communication": 4, "CRM": 3, "Negotiation": 3, "Lead Generation": 2}', 16),
(22, 'Senior Sales Manager', 'Sales', 'Senior', '{"Sales Strategy": 4, "Team Management": 4, "Client Relations": 4, "Revenue Planning": 3}', 42),
(23, 'Operations Manager', 'Operations', 'Senior', '{"Process Optimization": 4, "Team Leadership": 4, "Budget Management": 3, "Quality Control": 3}', 38),
(24, 'Mobile Developer', 'Engineering', 'Mid', '{"React Native": 4, "iOS": 3, "Android": 3, "Mobile UI": 3}', 26),
(25, 'Cloud Architect', 'Infrastructure', 'Senior', '{"AWS": 4, "Azure": 4, "Cloud Design": 4, "Security": 3}', 44);